MultiLang/Models/ErrorViewModel.cs
namespace MultiLang.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MultiLang/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using MultiLang.Models;

namespace MultiLang.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        public IActionResult Hr()
        {
            return View();
        }
        public IActionResult Crm()
        {
            return View();
        }
        public IActionResult Inventory()
        {
            return View();
        }
    }
}

MultiLang/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace MultiLang.Controllers
{
    public class LanguageController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append( /// for welcome and message
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            Response.Cookies.Append( /// for dropdown
                "SelectedCulture",
                culture,
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

MultiLang/Views/Home/Crm.cshtml
@using MultiLang.Crm
@inject Microsoft.Extensions.Localization.IStringLocalizer<CrmResource> LLocalizer


<h1>Crm</h1>

<p>@LLocalizer["Welcome to CRM"]</p>


<h1 class="btn btn-outline-danger">@Localizer["Save"]</h1>
<h1 class="btn btn-outline-dark">@Localizer["Delete"]</h1>

MultiLang/Views/Home/Hr.cshtml
@using MultiLang.Hr
@inject Microsoft.Extensions.Localization.IStringLocalizer<HrResource> LLocalizer

<h1>Hr</h1>

<p>@LLocalizer["Welcome to Hr"]</p>

<h1 class="btn btn-outline-danger">@Localizer["Save"]</h1>
<h1 class="btn btn-outline-dark">@Localizer["Delete"]</h1>

MultiLang/Views/Home/Index.cshtml
<h1 class="">@Localizer["Hello"]</h1>
<p>@Localizer["Message"]</p>


<h1 class="btn btn-outline-danger">@Localizer["Save"]</h1>
<h1 class="btn btn-outline-dark">@Localizer["Delete"]</h1>

MultiLang/Views/Home/Inventory.cshtml
@using MultiLang.Inventory
@inject Microsoft.Extensions.Localization.IStringLocalizer<InventoryResource> LLocalizer

<h1>Inventory</h1>
<p>@LLocalizer["Welcome to Inventory"]</p>


<h1 class="btn btn-outline-danger">@Localizer["Save"]</h1>
<h1 class="btn btn-outline-dark">@Localizer["Delete"]</h1>

MultiLang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MultiLang</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MultiLang.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MultiLang</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Crm">Crm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Hr">Hr</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Inventory">Inventory</a>
                        </li>

                    </ul>
                    <button class="btn btn-outline-danger">
                        @using Microsoft.AspNetCore.Localization
                        @{
                            var requestCulture = Context.Features.Get<IRequestCultureFeature>();
                            var currentCulture = requestCulture?.RequestCulture.UICulture.TwoLetterISOLanguageName ?? "en";
                        }
                        <form asp-controller="Language" asp-action="SetLanguage" method="post" class="d-inline">
                            <select name="culture" class=" btn btn-outline-dark" onchange="this.form.submit()">
                                <option value="en" selected="@(currentCulture == "en")">English   </option>
                                <option value="fr" selected="@(currentCulture == "fr")">French   </option>
                                <option value="es" selected="@(currentCulture == "es")">Spanish   </option>
                                <option value="bn" selected="@(currentCulture == "bn")">Bangla   </option>
                            </select>
                            <input type="hidden" name="returnUrl" value="@Context.Request.Path" />
                        </form>
                    </button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MultiLang - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>